### ISSUE TITLE
svg是用什么工具弄的，求解

### ISSUE THREAD

**Issue by lufinka** [hbxywdk/eleme-vue2#1]

**Comment by jiankafei** [comment]
在icon-font网站生成

**Comment by lufinka** [comment]
我知道http://www.iconfont.cn/这个网站，但是下载下来的svg代码很多，不像你的很简短

**Comment by jiankafei** [comment]
https://jakearchibald.github.io/svgomg/
使用这个在线压缩工具就行了

**Comment by jiankafei** [comment]
或者使用这个Node工具 https://github.com/svg/svgo

**Comment by hbxywdk** [comment]
抱歉这个demo当时做完后，就几乎没有在来看过了，demo中的svg都是直接copy饿了么H5中的，上面几位同学也给出了很多在线生成svg的网站可以参考。
