### ISSUE TITLE
求饿了么移动端高清适配

### ISSUE THREAD

**Issue by xvinc** [hbxywdk/eleme-vue2#2]
感觉比真实饿了么适配还好，一直感觉有点复杂不知像素多少

**Comment by hbxywdk** [comment]
这个demo做完了就很少来看，现在回复很抱歉。
首先，demo使用rem布局这个不用说了，然后根据window.devicePixelRatio的不同设置不同的'meta[name=viewport]缩放，希望能帮到你。
